# Generated by Django 6.0.2 on 2026-04-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staff_last_login_student_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='account_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='account_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
