# Generated by Django 6.0.2 on 2026-04-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staff_account_created_student_account_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='account_created',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='account_created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
    ]
