# Generated by Django 6.0.2 on 2026-04-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_staff_account_created_remove_staff_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staffId',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentId',
            new_name='user_id',
        ),
    ]
