# Generated by Django 6.0.2 on 2026-04-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_staffid_staff_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('uniform', 'Uniform'), ('id', 'ID / Lace'), ('supplies', 'Supplies')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='📦', max_length=10)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('oos', 'Out of Stock')], default='in_stock', max_length=20)),
                ('restock_date', models.DateField(blank=True, null=True)),
                ('sizes', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BaoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_user_id', models.CharField(max_length=9)),
                ('student_section', models.CharField(blank=True, max_length=50)),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('order_number', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Claiming'), ('claimed', 'Claimed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_user_id', models.CharField(max_length=9)),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('student_section', models.CharField(blank=True, max_length=50)),
                ('appt_number', models.CharField(max_length=10, unique=True)),
                ('service', models.CharField(choices=[('checkup', 'Physical Check-up'), ('records', 'Medical Record Processing')], max_length=20)),
                ('appt_date', models.DateField()),
                ('time_slot', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('attending_staff', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['appt_date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='BaoOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.baoorder')),
            ],
        ),
    ]
