# Generated by Django 6.0.2 on 2026-04-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_baoitem_baoorder_clinicappointment_baoorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_user_id', models.CharField(max_length=9)),
                ('poster_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('books', 'Books / Modules'), ('uniform', 'Uniform / Clothing'), ('electronics', 'Electronics'), ('merch', 'Merch / Accessories'), ('food', 'Food / Snacks'), ('services', 'Services'), ('other', 'Other')], default='other', max_length=20)),
                ('condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Used', 'Used'), ('For Free', 'For Free')], default='Good', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('is_event', models.BooleanField(default=False)),
                ('event_label', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('removed', 'Removed')], default='available', max_length=20)),
                ('removed_by', models.CharField(blank=True, max_length=100)),
                ('removed_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SCModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_user_id', models.CharField(max_length=9, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(blank=True, max_length=200)),
                ('granted_by', models.CharField(max_length=100)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='SCModeratorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_user_id', models.CharField(max_length=9)),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
