# Generated by Django 6.0.2 on 2026-04-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sclisting_scmoderator_scmoderatorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(choices=[('N', 'None'), ('C', 'Clinic'), ('B', 'Bao')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='student_staff_role',
            field=models.BooleanField(default=False),
        ),
    ]
