# Generated by Django 6.0.2 on 2026-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_staff_staff_role_student_student_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='isNew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='isNew',
            field=models.BooleanField(default=False),
        ),
    ]
