# Generated by Django 6.0.2 on 2026-05-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_staff_isnew_student_isnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_user_id', models.CharField(db_index=True, max_length=9)),
                ('notif_type', models.CharField(choices=[('bao_restock', 'BAO Item Restocked'), ('clinic', 'Clinic Appointment Reminder'), ('sc_reserved', 'Listing Reserved'), ('sc_contacted', 'Listing Contacted')], max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
