# Generated by Django 6.0.2 on 2026-05-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='baoitem',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
