# Generated by Django 6.0.2 on 2026-05-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_student_contact_num_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
