# Generated by Django 6.0.2 on 2026-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_student_profile_picture_b64'),
    ]

    operations = [
        migrations.AddField(
            model_name='sclisting',
            name='reserved_by_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sclisting',
            name='reserved_by_user_id',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('bao_order', 'BAO Order Update'), ('bao_restock', 'BAO Item Restocked'), ('clinic', 'Clinic Appointment Reminder'), ('sc_reserved', 'Listing Reserved'), ('sc_contacted', 'Listing Contacted')], max_length=20),
        ),
    ]
